//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Tecnica_Sistran.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personas
    {
        [Display(Name = "ID: ")]
        public int ID { get; set; }
        [Display(Name = "Documento de identidad: ")]
        public string Documento { get; set; }
        [Display(Name = "Nombres: ")]
        public string Nombres { get; set; }
        [Display(Name = "Apellidos: ")]
        public string Apellidos { get; set; }
        [Display(Name = "Fecha de Nacimiento: ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString ="{0:mm/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime FechaNacimiento { get; set; }
        [Display(Name = "Correo Electronico Principal: ")]
        public string Correo1 { get; set; }
        [Display(Name = "Correo Electronico Opcional: ")]
        public string Correo2 { get; set; }
        [Display(Name = "Direccion Principal: ")]
        public string Direccion1 { get; set; }
        [Display(Name = "Direccion Opcional: ")]
        public string Direccion2 { get; set; }
        [Display(Name = "Telefono Principal: ")]
        public string Telefono1 { get; set; }
        [Display(Name = "Telefono Opcional: ")]
        public string Telefono2 { get; set; }
    }
}
